# Generated by Django 5.2.5 on 2025-10-13 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertiser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "attribution",
                    models.CharField(
                        choices=[("Coupon", "Coupon"), ("Link", "Link")], max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DrNutritionTransaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_id", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField()),
                ("status", models.CharField(max_length=100)),
                ("delivery_status", models.CharField(max_length=100)),
                ("payment_method", models.CharField(max_length=100)),
                ("shipping_method", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("campaign", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("product", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("commission", models.DecimalField(decimal_places=2, max_digits=12)),
                ("logs", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("AFF", "Affiliate"),
                            ("INF", "Influencer"),
                            ("MB", "Media Buying"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.CreateModel(
            name="PartnerizeConversion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversion_id", models.CharField(max_length=100, unique=True)),
                (
                    "campaign_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("conversion_time", models.DateTimeField()),
                ("country", models.CharField(blank=True, max_length=10, null=True)),
                ("total_order_value", models.FloatField(blank=True, null=True)),
                ("total_commission", models.FloatField(blank=True, null=True)),
                (
                    "conversion_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("voucher", models.CharField(blank=True, max_length=100, null=True)),
                ("first_time_user", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdvertiserRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geo", models.CharField(max_length=50)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("FTU", "First Time User"), ("RTU", "Returning User")],
                        max_length=10,
                    ),
                ),
                ("rate_value", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("flat", "Flat")],
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        db_column="advertiser_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="api.advertiser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("affiliate", "Affiliate"),
                            ("influencer", "Influencer"),
                            ("media_buying", "Media Buying"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "department_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_members",
                        to="api.companyuser",
                    ),
                ),
                (
                    "ops_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_team_members",
                        to="api.companyuser",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.companyrole",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("geo", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="api.advertiser",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="api.partner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClickRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("affiliate", "Affiliate"),
                            ("influencer", "Influencer"),
                            ("media_buying", "Media Buying"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("destination_url", models.URLField(max_length=500)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advertiser"
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.companyuser",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.partner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advertisers",
                    models.ManyToManyField(blank=True, to="api.advertiser"),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.companyuser",
                    ),
                ),
                ("partners", models.ManyToManyField(blank=True, to="api.partner")),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="First day of month, e.g. 2025-10-01"),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("MB", "Media Buyer"),
                            ("AFF", "Affiliate"),
                            ("INF", "Influencer"),
                        ],
                        max_length=3,
                    ),
                ),
                ("orders_target", models.IntegerField()),
                (
                    "revenue_target",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("profit_target", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "spend_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_targets",
                        to="api.advertiser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target",
                "verbose_name_plural": "Targets",
                "unique_together": {("month", "advertiser", "partner_type")},
            },
        ),
        migrations.CreateModel(
            name="MediaBuyerDailySpend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount_spent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_spends",
                        to="api.advertiser",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_spends",
                        to="api.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Buyer Daily Spend",
                "unique_together": {("date", "advertiser", "partner")},
            },
        ),
        migrations.CreateModel(
            name="PartnerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ftu_payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "rtu_payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("flat", "Flat")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="api.advertiser",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="api.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Payout",
                "verbose_name_plural": "Partner Payouts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("advertiser", "partner"),
                        name="uniq_advertiser_partner_payout",
                    )
                ],
            },
        ),
    ]
