# Generated by Django 5.2.5 on 2025-10-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("geo", models.CharField(blank=True, max_length=10, null=True)),
                ("ftu_orders", models.IntegerField(default=0)),
                ("rtu_orders", models.IntegerField(default=0)),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "ftu_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rtu_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ftu_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rtu_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ftu_payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rtu_payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="api.advertiser",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_records",
                        to="api.coupon",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_records",
                        to="api.partner",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "advertiser", "partner", "coupon")},
            },
        ),
    ]
