# Generated by Django 5.2.5 on 2025-10-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_campaignperformance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
