# Generated by Django 5.2.5 on 2025-10-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_coupon_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignperformance",
            name="advertiser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_records",
                to="api.advertiser",
            ),
        ),
    ]
