# Generated by Django 5.2.5 on 2025-10-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_campaignperformance_advertiser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="campaignperformance",
            unique_together={("date", "advertiser", "partner", "coupon", "geo")},
        ),
    ]
