# Generated by Django 5.2.5 on 2025-10-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_campaignperformance_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="campaignperformance",
            unique_together=set(),
        ),
    ]
