# Generated by Django 5.2.5 on 2025-10-23 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_couponassignmenthistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couponassignmenthistory",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name='couponassignmenthistory',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partner', null=True),
        ),
        
    ]
