# Generated by Django 5.2.5 on 2025-10-23 07:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_couponassignmenthistory_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponassignmenthistory",
            name="assigned_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="couponassignmenthistory",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_assignments",
                to="api.partner",
            ),
        ),
    ]
