# Generated by Django 5.2.5 on 2025-10-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_couponassignmenthistory_assigned_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="partnerpayout",
            name="uniq_advertiser_partner_payout",
        ),
        migrations.AddField(
            model_name="partnerpayout",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnerpayout",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="partnerpayout",
            constraint=models.UniqueConstraint(
                fields=("advertiser", "partner", "start_date"),
                name="uniq_advertiser_partner_payout_period",
            ),
        ),
    ]
