# Generated by Django 5.2.5 on 2025-11-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_partnerpayout_uniq_advertiser_partner_payout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawAdvertiserRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Where the raw data came from (API, CSV, Sheet, etc.)",
                        max_length=100,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "data",
                    models.JSONField(
                        help_text="Full raw data snapshot in JSON format (unmodified)."
                    ),
                ),
                ("date_fetched", models.DateTimeField(auto_now_add=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="api.advertiser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Advertiser Snapshot",
                "verbose_name_plural": "Raw Advertiser Snapshots",
                "ordering": ["-date_fetched"],
            },
        ),
    ]
