# Generated by Django 5.2.5 on 2025-11-10 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rawadvertiserrecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drnutritiontransaction",
            old_name="code",
            new_name="coupon",
        ),
        migrations.RemoveField(
            model_name="advertiserrate",
            name="rate_value",
        ),
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="logs",
        ),
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="product",
        ),
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="selling_price",
        ),
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="shipping_method",
        ),
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="status",
        ),
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="type",
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="advertiser_name",
            field=models.CharField(default="Unknown", max_length=150),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="currency",
            field=models.CharField(default="AED", max_length=10),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="date",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="ftu_orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="ftu_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="partner_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="partner_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="payout",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="payout_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="profit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="profit_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="rate_type",
            field=models.CharField(default="percent", max_length=20),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="rtu_orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="rtu_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="sales",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="user_type",
            field=models.CharField(default="FTU", max_length=10),
        ),
        migrations.AlterField(
            model_name="advertiserrate",
            name="user_type",
            field=models.CharField(default="FTU", max_length=10),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="created_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
