# Generated by Django 5.2.5 on 2025-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_code_drnutritiontransaction_coupon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="delivery_status",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
