# Generated by Django 5.2.5 on 2025-11-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_drnutritiontransaction_delivery_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drnutritiontransaction",
            name="date",
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="advertiser_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="commission",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="country",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="currency",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="order_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="orders",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="rate_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="sales",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="drnutritiontransaction",
            name="user_type",
            field=models.CharField(max_length=10),
        ),
    ]
