# Generated by Django 5.2.5 on 2025-11-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_stylitransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignperformance",
            name="ftu_our_rev",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="campaignperformance",
            name="rtu_our_rev",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="campaignperformance",
            name="total_our_rev",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="drnutritiontransaction",
            name="our_rev",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="stylitransaction",
            name="our_rev",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
