# Generated by Django 5.2.5 on 2025-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_campaignperformance_ftu_our_rev_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertiser",
            name="rev_ftu_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="advertiser",
            name="rev_rate_type",
            field=models.CharField(
                choices=[("percent", "Percent"), ("fixed", "Fixed")],
                default="percent",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="advertiser",
            name="rev_rtu_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
