# Generated by Django 5.2.5 on 2025-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_advertiser_rev_ftu_rate_advertiser_rev_rate_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertiser",
            name="currency",
            field=models.CharField(
                choices=[
                    ("AED", "AED"),
                    ("SAR", "SAR"),
                    ("EGP", "EGP"),
                    ("USD", "USD"),
                ],
                default="AED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="advertiser",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="How many USD per 1 unit of advertiser's currency",
                max_digits=10,
                null=True,
            ),
        ),
    ]
