# Generated by Django 5.2.5 on 2025-11-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_springrosetransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpayout",
            name="ftu_fixed_bonus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="partnerpayout",
            name="rtu_fixed_bonus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
