# Generated by Django 5.2.5 on 2025-11-12 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_partnerpayout_ftu_fixed_bonus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoonNamshiTransaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_id", models.BigIntegerField(default=0)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_status",
                    models.CharField(
                        blank=True, default="delivered", max_length=100, null=True
                    ),
                ),
                ("country", models.CharField(max_length=10)),
                ("coupon", models.CharField(max_length=50)),
                ("user_type", models.CharField(max_length=10)),
                (
                    "partner_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "partner_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("advertiser_name", models.CharField(max_length=150)),
                ("currency", models.CharField(max_length=10)),
                ("rate_type", models.CharField(max_length=20)),
                (
                    "sales",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "our_rev",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("ftu_orders", models.IntegerField(default=0)),
                ("rtu_orders", models.IntegerField(default=0)),
                ("orders", models.IntegerField(default=1)),
                (
                    "ftu_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "rtu_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "payout",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "payout_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "profit_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
            ],
        ),
    ]
