# Generated by Django 5.2.5 on 2025-11-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_noonnamshitransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertiser",
            name="default_ftu_payout",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default FTU payout for all partners",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="advertiser",
            name="default_payout_rate_type",
            field=models.CharField(
                choices=[("percent", "Percent"), ("fixed", "Fixed")],
                default="percent",
                help_text="Default payout type for all partners",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="advertiser",
            name="default_rtu_payout",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default RTU payout for all partners",
                max_digits=6,
                null=True,
            ),
        ),
    ]
