# Generated by Django 5.2.5 on 2025-11-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_advertiser_default_ftu_payout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertiser",
            name="rev_ftu_fixed_bonus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed bonus per FTU order (e.g., 3 AED)",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="advertiser",
            name="rev_rtu_fixed_bonus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed bonus per RTU order",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="rev_ftu_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="FTU revenue rate (% or fixed amount)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="rev_rate_type",
            field=models.CharField(
                choices=[("percent", "Percent"), ("fixed", "Fixed")],
                default="percent",
                help_text="Percent or Fixed per order",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="rev_rtu_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="RTU revenue rate (% or fixed amount)",
                max_digits=6,
                null=True,
            ),
        ),
    ]
