# Generated by Django 5.2.5 on 2025-11-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_advertiser_rev_ftu_fixed_bonus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertiser",
            name="default_ftu_fixed_bonus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default fixed bonus per FTU order for all partners (e.g., 3 AED)",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="advertiser",
            name="default_rtu_fixed_bonus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default fixed bonus per RTU order for all partners",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="default_ftu_payout",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default FTU payout for all partners (% or fixed)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="default_rtu_payout",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default RTU payout for all partners (% or fixed)",
                max_digits=6,
                null=True,
            ),
        ),
    ]
