# Generated by Django 5.2.5 on 2025-11-19 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_advertiser_default_ftu_fixed_bonus_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mediabuyerdailyspend",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mediabuyerdailyspend",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_spends",
                to="api.coupon",
            ),
        ),
        migrations.AddField(
            model_name="mediabuyerdailyspend",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Meta", "Meta (Facebook/Instagram)"),
                    ("Snapchat", "Snapchat"),
                    ("TikTok", "TikTok"),
                    ("Google", "Google Ads"),
                    ("Twitter", "Twitter/X"),
                    ("LinkedIn", "LinkedIn"),
                    ("YouTube", "YouTube"),
                    ("Other", "Other"),
                ],
                default="Meta",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediabuyerdailyspend",
            unique_together={("date", "advertiser", "partner", "coupon", "platform")},
        ),
    ]
