# Generated by Django 5.2.5 on 2025-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_payoutrulehistory_revenuerulehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerizeconversion",
            name="advertiser_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="commission",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="ftu_orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="ftu_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="our_rev",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="partner_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="partner_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="payout",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="payout_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="profit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="profit_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="rate_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="rtu_orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="rtu_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="partnerizeconversion",
            name="sales",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="coupon",
            unique_together={("code", "advertiser")},
        ),
    ]
