# Generated by Django 5.2.5 on 2025-11-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_partnerizeconversion_advertiser_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="departmenttarget",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="departmenttarget",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for department-level target, select for individual team member target",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_targets",
                to="api.companyuser",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmenttarget",
            unique_together={("month", "advertiser", "partner_type", "assigned_to")},
        ),
    ]
