# Generated by Django 5.2.5 on 2025-12-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_sheet_sync_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='noonnamshitransaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noon_namshi_transactions', to='api.partner'),
        ),
        migrations.AddField(
            model_name='stylitransaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noonnamshi_txns', to='api.partner'),
        ),
        migrations.AlterField(
            model_name='departmenttarget',
            name='profit_target',
            field=models.DecimalField(decimal_places=2, help_text='Auto-calculated as revenue_target - spend_target', max_digits=12),
        ),
        migrations.AlterField(
            model_name='departmenttarget',
            name='spend_target',
            field=models.DecimalField(decimal_places=2, help_text='Required for calculating profit', max_digits=12),
        ),
        migrations.AlterField(
            model_name='rdeltransaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noonnamshi_transactions', to='api.partner'),
        ),
    ]
