# Generated by Django 5.2.5 on 2025-12-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_noonnamshitransaction_partner_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS api_rdeltransaction CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
